REPETITA is designed with extensibility in mind.
The following pages detail how to 

- `add solvers`_, that is, traffic engineering algorithms
- `add scenarios`_, that is, experiments and analyses
- `add problem instances`_, that is, network topologies and traffic matrices


.. _`add solvers` :  https://github.com/stefanovis/repetita/wiki/Adding-Solvers
.. _`add scenarios` : https://github.com/stefanovis/repetita/wiki/Adding-Scenarios
.. _`add problem instances` : https://github.com/stefanovis/repetita/wiki/Adding-Problem-Instances
